// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCActionResult.h"
#include "action_result.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCActionResult;

namespace djinni_generated {

struct ActionResult
{
    using CppType = ::demo::ActionResult;
    using ObjcType = SCActionResult*;

    using Boxed = ActionResult;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
