// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCActionResult+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ActionResult::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.code),
            ::djinni::String::toCpp(obj.msg),
            ::djinni::String::toCpp(obj.data)};
}

auto ActionResult::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCActionResult alloc] initWithCode:(::djinni::I32::fromCpp(cpp.code))
                                            msg:(::djinni::String::fromCpp(cpp.msg))
                                           data:(::djinni::String::fromCpp(cpp.data))];
}

}  // namespace djinni_generated
