// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import <Foundation/Foundation.h>

/**login relation */
@interface SCActionResult : NSObject
- (nonnull instancetype)initWithCode:(int32_t)code
                                 msg:(nonnull NSString *)msg
                                data:(nonnull NSString *)data;
+ (nonnull instancetype)actionResultWithCode:(int32_t)code
                                         msg:(nonnull NSString *)msg
                                        data:(nonnull NSString *)data;

@property (nonatomic, readonly) int32_t code;

@property (nonatomic, readonly, nonnull) NSString * msg;

@property (nonatomic, readonly, nonnull) NSString * data;

@end
