// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCActionResult.h"
#import <Foundation/Foundation.h>


@protocol SCLoginListener

- (void)onLoginFinish:(nonnull SCActionResult *)result;

- (void)onSignFinish:(nonnull SCActionResult *)result;

- (void)onLogoutFinish:(nonnull SCActionResult *)result;

- (void)onCheckStatusFinish:(nonnull SCActionResult *)result;

- (void)onDisconnect:(nonnull SCActionResult *)result;

@end
