// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCLoginListener+Private.h"
#import "SCLoginListener.h"
#import "DJIObjcWrapperCache+Private.h"
#import "SCActionResult+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class LoginListener::ObjcProxy final
: public ::demo::LoginListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::LoginListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void on_login_finish(const ::demo::ActionResult & c_result) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoginFinish:(::djinni_generated::ActionResult::fromCpp(c_result))];
        }
    }
    void on_sign_finish(const ::demo::ActionResult & c_result) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onSignFinish:(::djinni_generated::ActionResult::fromCpp(c_result))];
        }
    }
    void on_logout_finish(const ::demo::ActionResult & c_result) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLogoutFinish:(::djinni_generated::ActionResult::fromCpp(c_result))];
        }
    }
    void on_check_status_finish(const ::demo::ActionResult & c_result) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onCheckStatusFinish:(::djinni_generated::ActionResult::fromCpp(c_result))];
        }
    }
    void on_disconnect(const ::demo::ActionResult & c_result) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onDisconnect:(::djinni_generated::ActionResult::fromCpp(c_result))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto LoginListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto LoginListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
