// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import <Foundation/Foundation.h>


@protocol SCLoginListener

- (void)onLoginFinish:(int32_t)code;

- (void)onSignFinish:(int32_t)code;

- (void)onLogoutFinish:(int32_t)code;

- (void)onCheckStatusFinish:(int32_t)code
                    account:(nonnull NSString *)account;

- (void)onDisconnect;

- (void)toast:(nonnull NSString *)content;

@end
