// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import <Foundation/Foundation.h>
@class SCLoginCore;
@protocol SCLoginListener;


@interface SCLoginCore : NSObject

+ (nullable SCLoginCore *)create:(nullable id<SCLoginListener>)listener;

- (void)userLogin:(nonnull NSString *)account
         password:(nonnull NSString *)password;

- (void)userSign:(nonnull NSString *)account
        password:(nonnull NSString *)password;

- (void)userLogout;

- (void)checkLoginStatus;

- (void)checkConnection;

@end
