// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#include "login_core.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCLoginCore;

namespace djinni_generated {

class LoginCore
{
public:
    using CppType = std::shared_ptr<::demo::LoginCore>;
    using CppOptType = std::shared_ptr<::demo::LoginCore>;
    using ObjcType = SCLoginCore*;

    using Boxed = LoginCore;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

