// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCUserAccount+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto UserAccount::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.id),
            ::djinni::String::toCpp(obj.account),
            ::djinni::String::toCpp(obj.password)};
}

auto UserAccount::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCUserAccount alloc] initWithId:(::djinni::String::fromCpp(cpp.id))
                                     account:(::djinni::String::fromCpp(cpp.account))
                                    password:(::djinni::String::fromCpp(cpp.password))];
}

}  // namespace djinni_generated
