// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCUserAccount.h"
#include "user_account.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCUserAccount;

namespace djinni_generated {

struct UserAccount
{
    using CppType = ::demo::UserAccount;
    using ObjcType = SCUserAccount*;

    using Boxed = UserAccount;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
