// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import "SCUserAccount.h"


@implementation SCUserAccount

- (nonnull instancetype)initWithId:(nonnull NSString *)id
                           account:(nonnull NSString *)account
                          password:(nonnull NSString *)password
{
    if (self = [super init]) {
        _id = [id copy];
        _account = [account copy];
        _password = [password copy];
    }
    return self;
}

+ (nonnull instancetype)userAccountWithId:(nonnull NSString *)id
                                  account:(nonnull NSString *)account
                                 password:(nonnull NSString *)password
{
    return [(SCUserAccount*)[self alloc] initWithId:id
                                            account:account
                                           password:password];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ account:%@ password:%@>", self.class, (void *)self, self.id, self.account, self.password];
}

@end
