// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#import <Foundation/Foundation.h>

/**login relation */
@interface SCUserAccount : NSObject
- (nonnull instancetype)initWithId:(nonnull NSString *)id
                           account:(nonnull NSString *)account
                          password:(nonnull NSString *)password;
+ (nonnull instancetype)userAccountWithId:(nonnull NSString *)id
                                  account:(nonnull NSString *)account
                                 password:(nonnull NSString *)password;

@property (nonatomic, readonly, nonnull) NSString * id;

@property (nonatomic, readonly, nonnull) NSString * account;

@property (nonatomic, readonly, nonnull) NSString * password;

@end
