// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: account.proto
#ifndef GRPC_account_2eproto__INCLUDED
#define GRPC_account_2eproto__INCLUDED

#include "account.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace account {

class Account final {
 public:
  static constexpr char const* service_full_name() {
    return "account.Account";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status requestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::account::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> AsyncrequestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(AsyncrequestUserLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> PrepareAsyncrequestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(PrepareAsyncrequestUserLoginRaw(context, request, cq));
    }
    virtual ::grpc::Status requestUserSign(::grpc::ClientContext* context, const ::account::SignRequest& request, ::account::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> AsyncrequestUserSign(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(AsyncrequestUserSignRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> PrepareAsyncrequestUserSign(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(PrepareAsyncrequestUserSignRaw(context, request, cq));
    }
    virtual ::grpc::Status checkConnect(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::account::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> AsynccheckConnect(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(AsynccheckConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> PrepareAsynccheckConnect(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(PrepareAsynccheckConnectRaw(context, request, cq));
    }
    virtual ::grpc::Status requestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::account::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> AsyncrequestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(AsyncrequestLogoutRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> PrepareAsyncrequestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(PrepareAsyncrequestLogoutRaw(context, request, cq));
    }
    virtual ::grpc::Status refreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::account::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> AsyncrefreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(AsyncrefreshTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>> PrepareAsyncrefreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>>(PrepareAsyncrefreshTokenRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void requestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestUserSign(::grpc::ClientContext* context, const ::account::SignRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void checkConnect(::grpc::ClientContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void refreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* AsyncrequestUserLoginRaw(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* PrepareAsyncrequestUserLoginRaw(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* AsyncrequestUserSignRaw(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* PrepareAsyncrequestUserSignRaw(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* AsynccheckConnectRaw(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* PrepareAsynccheckConnectRaw(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* AsyncrequestLogoutRaw(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* PrepareAsyncrequestLogoutRaw(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* AsyncrefreshTokenRaw(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::account::CodeReply>* PrepareAsyncrefreshTokenRaw(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status requestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::account::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> AsyncrequestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(AsyncrequestUserLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> PrepareAsyncrequestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(PrepareAsyncrequestUserLoginRaw(context, request, cq));
    }
    ::grpc::Status requestUserSign(::grpc::ClientContext* context, const ::account::SignRequest& request, ::account::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> AsyncrequestUserSign(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(AsyncrequestUserSignRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> PrepareAsyncrequestUserSign(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(PrepareAsyncrequestUserSignRaw(context, request, cq));
    }
    ::grpc::Status checkConnect(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::account::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> AsynccheckConnect(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(AsynccheckConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> PrepareAsynccheckConnect(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(PrepareAsynccheckConnectRaw(context, request, cq));
    }
    ::grpc::Status requestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::account::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> AsyncrequestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(AsyncrequestLogoutRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> PrepareAsyncrequestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(PrepareAsyncrequestLogoutRaw(context, request, cq));
    }
    ::grpc::Status refreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::account::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> AsyncrefreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(AsyncrefreshTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>> PrepareAsyncrefreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::account::CodeReply>>(PrepareAsyncrefreshTokenRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void requestUserLogin(::grpc::ClientContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void requestUserSign(::grpc::ClientContext* context, const ::account::SignRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void checkConnect(::grpc::ClientContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void requestLogout(::grpc::ClientContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void refreshToken(::grpc::ClientContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* AsyncrequestUserLoginRaw(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* PrepareAsyncrequestUserLoginRaw(::grpc::ClientContext* context, const ::account::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* AsyncrequestUserSignRaw(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* PrepareAsyncrequestUserSignRaw(::grpc::ClientContext* context, const ::account::SignRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* AsynccheckConnectRaw(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* PrepareAsynccheckConnectRaw(::grpc::ClientContext* context, const ::account::ConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* AsyncrequestLogoutRaw(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* PrepareAsyncrequestLogoutRaw(::grpc::ClientContext* context, const ::account::LogoutRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* AsyncrefreshTokenRaw(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::account::CodeReply>* PrepareAsyncrefreshTokenRaw(::grpc::ClientContext* context, const ::account::RefreshRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_requestUserLogin_;
    const ::grpc::internal::RpcMethod rpcmethod_requestUserSign_;
    const ::grpc::internal::RpcMethod rpcmethod_checkConnect_;
    const ::grpc::internal::RpcMethod rpcmethod_requestLogout_;
    const ::grpc::internal::RpcMethod rpcmethod_refreshToken_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response);
    virtual ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response);
    virtual ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response);
    virtual ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response);
    virtual ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_requestUserLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_requestUserLogin() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_requestUserLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestUserLogin(::grpc::ServerContext* context, ::account::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::account::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_requestUserSign : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_requestUserSign() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_requestUserSign() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestUserSign(::grpc::ServerContext* context, ::account::SignRequest* request, ::grpc::ServerAsyncResponseWriter< ::account::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_checkConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_checkConnect() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_checkConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcheckConnect(::grpc::ServerContext* context, ::account::ConnectRequest* request, ::grpc::ServerAsyncResponseWriter< ::account::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_requestLogout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_requestLogout() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_requestLogout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestLogout(::grpc::ServerContext* context, ::account::LogoutRequest* request, ::grpc::ServerAsyncResponseWriter< ::account::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_refreshToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_refreshToken() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_refreshToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrefreshToken(::grpc::ServerContext* context, ::account::RefreshRequest* request, ::grpc::ServerAsyncResponseWriter< ::account::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_requestUserLogin<WithAsyncMethod_requestUserSign<WithAsyncMethod_checkConnect<WithAsyncMethod_requestLogout<WithAsyncMethod_refreshToken<Service > > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestUserLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_requestUserLogin() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::account::LoginRequest, ::account::CodeReply>(
          [this](::grpc::ServerContext* context,
                 const ::account::LoginRequest* request,
                 ::account::CodeReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->requestUserLogin(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_requestUserLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestUserSign : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_requestUserSign() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::account::SignRequest, ::account::CodeReply>(
          [this](::grpc::ServerContext* context,
                 const ::account::SignRequest* request,
                 ::account::CodeReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->requestUserSign(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_requestUserSign() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_checkConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_checkConnect() {
      ::grpc::Service::experimental().MarkMethodCallback(2,
        new ::grpc::internal::CallbackUnaryHandler< ::account::ConnectRequest, ::account::CodeReply>(
          [this](::grpc::ServerContext* context,
                 const ::account::ConnectRequest* request,
                 ::account::CodeReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->checkConnect(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_checkConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestLogout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_requestLogout() {
      ::grpc::Service::experimental().MarkMethodCallback(3,
        new ::grpc::internal::CallbackUnaryHandler< ::account::LogoutRequest, ::account::CodeReply>(
          [this](::grpc::ServerContext* context,
                 const ::account::LogoutRequest* request,
                 ::account::CodeReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->requestLogout(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_requestLogout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_refreshToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_refreshToken() {
      ::grpc::Service::experimental().MarkMethodCallback(4,
        new ::grpc::internal::CallbackUnaryHandler< ::account::RefreshRequest, ::account::CodeReply>(
          [this](::grpc::ServerContext* context,
                 const ::account::RefreshRequest* request,
                 ::account::CodeReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->refreshToken(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_refreshToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_requestUserLogin<ExperimentalWithCallbackMethod_requestUserSign<ExperimentalWithCallbackMethod_checkConnect<ExperimentalWithCallbackMethod_requestLogout<ExperimentalWithCallbackMethod_refreshToken<Service > > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_requestUserLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_requestUserLogin() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_requestUserLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_requestUserSign : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_requestUserSign() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_requestUserSign() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_checkConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_checkConnect() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_checkConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_requestLogout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_requestLogout() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_requestLogout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_refreshToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_refreshToken() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_refreshToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestUserLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_requestUserLogin() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_requestUserLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestUserLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestUserSign : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_requestUserSign() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_requestUserSign() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestUserSign(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_checkConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_checkConnect() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_checkConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcheckConnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestLogout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_requestLogout() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_requestLogout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestLogout(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_refreshToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_refreshToken() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_refreshToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrefreshToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestUserLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_requestUserLogin() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->requestUserLogin(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_requestUserLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void requestUserLogin(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestUserSign : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_requestUserSign() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->requestUserSign(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_requestUserSign() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void requestUserSign(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_checkConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_checkConnect() {
      ::grpc::Service::experimental().MarkMethodRawCallback(2,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->checkConnect(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_checkConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void checkConnect(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestLogout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_requestLogout() {
      ::grpc::Service::experimental().MarkMethodRawCallback(3,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->requestLogout(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_requestLogout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void requestLogout(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_refreshToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_refreshToken() {
      ::grpc::Service::experimental().MarkMethodRawCallback(4,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->refreshToken(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_refreshToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void refreshToken(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestUserLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_requestUserLogin() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::account::LoginRequest, ::account::CodeReply>(std::bind(&WithStreamedUnaryMethod_requestUserLogin<BaseClass>::StreamedrequestUserLogin, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_requestUserLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestUserLogin(::grpc::ServerContext* context, const ::account::LoginRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestUserLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::LoginRequest,::account::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestUserSign : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_requestUserSign() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::account::SignRequest, ::account::CodeReply>(std::bind(&WithStreamedUnaryMethod_requestUserSign<BaseClass>::StreamedrequestUserSign, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_requestUserSign() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestUserSign(::grpc::ServerContext* context, const ::account::SignRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestUserSign(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::SignRequest,::account::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_checkConnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_checkConnect() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::account::ConnectRequest, ::account::CodeReply>(std::bind(&WithStreamedUnaryMethod_checkConnect<BaseClass>::StreamedcheckConnect, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_checkConnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status checkConnect(::grpc::ServerContext* context, const ::account::ConnectRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcheckConnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::ConnectRequest,::account::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestLogout : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_requestLogout() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler< ::account::LogoutRequest, ::account::CodeReply>(std::bind(&WithStreamedUnaryMethod_requestLogout<BaseClass>::StreamedrequestLogout, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_requestLogout() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestLogout(::grpc::ServerContext* context, const ::account::LogoutRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestLogout(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::LogoutRequest,::account::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_refreshToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_refreshToken() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler< ::account::RefreshRequest, ::account::CodeReply>(std::bind(&WithStreamedUnaryMethod_refreshToken<BaseClass>::StreamedrefreshToken, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_refreshToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status refreshToken(::grpc::ServerContext* context, const ::account::RefreshRequest* request, ::account::CodeReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrefreshToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::account::RefreshRequest,::account::CodeReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_requestUserLogin<WithStreamedUnaryMethod_requestUserSign<WithStreamedUnaryMethod_checkConnect<WithStreamedUnaryMethod_requestLogout<WithStreamedUnaryMethod_refreshToken<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_requestUserLogin<WithStreamedUnaryMethod_requestUserSign<WithStreamedUnaryMethod_checkConnect<WithStreamedUnaryMethod_requestLogout<WithStreamedUnaryMethod_refreshToken<Service > > > > > StreamedService;
};

}  // namespace account


#endif  // GRPC_account_2eproto__INCLUDED
