// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

package com.wechat.clibs;

/**login relation */
public final class ActionResult {


    /*package*/ final int mCode;

    /*package*/ final String mMsg;

    /*package*/ final String mData;

    public ActionResult(
            int code,
            String msg,
            String data) {
        this.mCode = code;
        this.mMsg = msg;
        this.mData = data;
    }

    public int getCode() {
        return mCode;
    }

    public String getMsg() {
        return mMsg;
    }

    public String getData() {
        return mData;
    }

    @Override
    public String toString() {
        return "ActionResult{" +
                "mCode=" + mCode +
                "," + "mMsg=" + mMsg +
                "," + "mData=" + mData +
        "}";
    }

}
