// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

package com.wechat.clibs;

public abstract class LoginListener {
    public abstract void onLoginFinish(ActionResult result);

    public abstract void onSignFinish(ActionResult result);

    public abstract void onLogoutFinish(ActionResult result);

    public abstract void onCheckStatusFinish(ActionResult result);

    public abstract void onDisconnect(ActionResult result);
}
