// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

package com.wechat.clibs;

/**login relation */
public final class UserAccount {


    /*package*/ final String mId;

    /*package*/ final String mAccount;

    /*package*/ final String mPassword;

    public UserAccount(
            String id,
            String account,
            String password) {
        this.mId = id;
        this.mAccount = account;
        this.mPassword = password;
    }

    public String getId() {
        return mId;
    }

    public String getAccount() {
        return mAccount;
    }

    public String getPassword() {
        return mPassword;
    }

    @Override
    public String toString() {
        return "UserAccount{" +
                "mId=" + mId +
                "," + "mAccount=" + mAccount +
                "," + "mPassword=" + mPassword +
        "}";
    }

}
