// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#pragma once

#include "djinni_support.hpp"
#include "login_core.hpp"

namespace djinni_generated {

class NativeLoginCore final : ::djinni::JniInterface<::demo::LoginCore, NativeLoginCore> {
public:
    using CppType = std::shared_ptr<::demo::LoginCore>;
    using CppOptType = std::shared_ptr<::demo::LoginCore>;
    using JniType = jobject;

    using Boxed = NativeLoginCore;

    ~NativeLoginCore();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLoginCore>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLoginCore>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLoginCore();
    friend ::djinni::JniClass<NativeLoginCore>;
    friend ::djinni::JniInterface<::demo::LoginCore, NativeLoginCore>;

};

}  // namespace djinni_generated
