// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#pragma once

#include "djinni_support.hpp"
#include "login_listener.hpp"

namespace djinni_generated {

class NativeLoginListener final : ::djinni::JniInterface<::demo::LoginListener, NativeLoginListener> {
public:
    using CppType = std::shared_ptr<::demo::LoginListener>;
    using CppOptType = std::shared_ptr<::demo::LoginListener>;
    using JniType = jobject;

    using Boxed = NativeLoginListener;

    ~NativeLoginListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLoginListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLoginListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLoginListener();
    friend ::djinni::JniClass<NativeLoginListener>;
    friend ::djinni::JniInterface<::demo::LoginListener, NativeLoginListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::demo::LoginListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void on_login_finish(const ::demo::ActionResult & result) override;
        void on_sign_finish(const ::demo::ActionResult & result) override;
        void on_logout_finish(const ::demo::ActionResult & result) override;
        void on_check_status_finish(const ::demo::ActionResult & result) override;
        void on_disconnect(const ::demo::ActionResult & result) override;

    private:
        friend ::djinni::JniInterface<::demo::LoginListener, ::djinni_generated::NativeLoginListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/wechat/clibs/LoginListener") };
    const jmethodID method_onLoginFinish { ::djinni::jniGetMethodID(clazz.get(), "onLoginFinish", "(Lcom/wechat/clibs/ActionResult;)V") };
    const jmethodID method_onSignFinish { ::djinni::jniGetMethodID(clazz.get(), "onSignFinish", "(Lcom/wechat/clibs/ActionResult;)V") };
    const jmethodID method_onLogoutFinish { ::djinni::jniGetMethodID(clazz.get(), "onLogoutFinish", "(Lcom/wechat/clibs/ActionResult;)V") };
    const jmethodID method_onCheckStatusFinish { ::djinni::jniGetMethodID(clazz.get(), "onCheckStatusFinish", "(Lcom/wechat/clibs/ActionResult;)V") };
    const jmethodID method_onDisconnect { ::djinni::jniGetMethodID(clazz.get(), "onDisconnect", "(Lcom/wechat/clibs/ActionResult;)V") };
};

}  // namespace djinni_generated
