// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#pragma once

#include "djinni_support.hpp"
#include "user_account.hpp"

namespace djinni_generated {

class NativeUserAccount final {
public:
    using CppType = ::demo::UserAccount;
    using JniType = jobject;

    using Boxed = NativeUserAccount;

    ~NativeUserAccount();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeUserAccount();
    friend ::djinni::JniClass<NativeUserAccount>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/wechat/clibs/UserAccount") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/String;") };
    const jfieldID field_mAccount { ::djinni::jniGetFieldID(clazz.get(), "mAccount", "Ljava/lang/String;") };
    const jfieldID field_mPassword { ::djinni::jniGetFieldID(clazz.get(), "mPassword", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
