// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#pragma once

namespace demo {

struct ActionResult;

class LoginListener {
public:
    virtual ~LoginListener() {}

    virtual void on_login_finish(const ActionResult & result) = 0;

    virtual void on_sign_finish(const ActionResult & result) = 0;

    virtual void on_logout_finish(const ActionResult & result) = 0;

    virtual void on_check_status_finish(const ActionResult & result) = 0;

    virtual void on_disconnect(const ActionResult & result) = 0;
};

}  // namespace demo
