// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from demo.djinni

#pragma once

#include <string>
#include <utility>

namespace demo {

/**login relation */
struct UserAccount final {
    std::string id;
    std::string account;
    std::string password;

    UserAccount(std::string id_,
                std::string account_,
                std::string password_)
    : id(std::move(id_))
    , account(std::move(account_))
    , password(std::move(password_))
    {}
};

}  // namespace demo
